In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('dog_breed_classification.csv')
df

Ear Flap Length   Ear flap Width  Breed No 
0                6.3             3.6          1
1                6.6             2.6          3
2                8.6             3.0          2
3                6.5             3.3          1
4                6.3             3.2          1
5                6.5             3.4          1
6                8.8             2.8          2
7                7.3             2.6          3
8                6.3             2.4          3
9                7.2             2.6          3
10               7.0             2.9          2
11               7.6             2.2          3
12               6.2             3.7          1
13               7.7             2.3          3
14               8.7             2.9          2

In [ ]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

Training the K-NN model on the Training set (k=3)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn_3 = KNeighborsClassifier(n_neighbors = 3, metric = 'euclidean')
classifier_knn_3.fit(x, y)

KNeighborsClassifier(metric='euclidean', n_neighbors=3)

Training the K-NN model on the Training set (k=5)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn_5 = KNeighborsClassifier(n_neighbors = 5, metric = 'euclidean')
classifier_knn_5.fit(x, y)

KNeighborsClassifier(metric='euclidean')

predicting for Ear flap length=6.3 inches,  Ear flap width=3.1 inches.

In [ ]:
classifier_knn_3.predict([[6.3,3.1]])

array([1])

In [ ]:
classifier_knn_5.predict([[6.3,3.1]])

array([1])

confusion matrix

In [ ]:
y_pred = classifier_knn_5.predict(x)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y, y_pred)
cm

array([[5, 0, 0],
       [0, 3, 1],
       [1, 0, 5]])

In [ ]:
accuracy_score(y, y_pred)

0.8666666666666667