In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
x = np.array([5, 5.25, 5.5, 5.75, 6, 6.5, 7, 7.5, 8, 8.5, 8.75, 9])
y = np.array([0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0])

In [3]:
x = x.reshape(-1,1)

In [4]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x, y)

LogisticRegression(random_state=0)

In [5]:
classifier.predict([[5.5]])

array([0])

In [6]:
classifier.predict([[5.75]])

array([1])

In [7]:
y_pred = classifier.predict(x)
print(np.concatenate((y.reshape(len(y),1), (y_pred.reshape(len(y_pred),1))),1))

[[0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]]


In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score
cm = confusion_matrix(y, y_pred)
print(cm)

[[2 3]
 [1 6]]


In [16]:
accuracy_score(y, y_pred)

0.6666666666666666

In [12]:
precision_score(y, y_pred)

0.6666666666666666

In [14]:
recall_score(y, y_pred)

0.8571428571428571

In [11]:
f1_score(y, y_pred)

0.75